// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class CustomerServiceLinkTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void customerServiceLink() {
    // Test name: customerServiceLink
    // Step # | name | target | value
    // 1 | open | https://www.sportchek.ca/ | 
    driver.get("https://www.sportchek.ca/");
    // 2 | setWindowSize | 1595x922 | 
    driver.manage().window().setSize(new Dimension(1595, 922));
    // 3 | mouseOver | linkText=Wellness | 
    // Move mouse and scroll to the bottom of the page
    {
      WebElement element = driver.findElement(By.linkText("Wellness"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 4 | mouseOut | linkText=Wellness | 
    // Move mouse and scroll to the bottom of the page
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 5 | mouseOver | linkText=Jerseys & Fan Wear | 
    // Move mouse and scroll to the bottom of the page
    {
      WebElement element = driver.findElement(By.linkText("Jerseys & Fan Wear"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 6 | mouseOut | linkText=Jerseys & Fan Wear | 
    // Move mouse and scroll to the bottom of the page
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 7 | runScript | window.scrollTo(0,16724) | 
    // Move mouse and scroll to the bottom of the page
    js.executeScript("window.scrollTo(0,16724)");
    // 8 | assertText | css=.customerServiceLinks .footer-section__head | CUSTOMER SERVICE
    // Assert the Customer Service Heaher is present in the site nav
    assertThat(driver.findElement(By.cssSelector(".customerServiceLinks .footer-section__head")).getText(), is("CUSTOMER SERVICE"));
    // 9 | click | linkText=Online Customer Service | 
    // Click on the Customer service link
    driver.findElement(By.linkText("Online Customer Service")).click();
    // 10 | assertText | css=.global-page-header__title | ONLINE STORE INFORMATION
    // Check that the Online Store Information page header is present
    assertThat(driver.findElement(By.cssSelector(".global-page-header__title")).getText(), is("ONLINE STORE INFORMATION"));
    // 11 | assertText | css=.section-header__title | Contact Us
    // Check that the 'Contact Us' header is present
    assertThat(driver.findElement(By.cssSelector(".section-header__title")).getText(), is("Contact Us"));
    // 12 | assertElementPresent | css=.contact-us__button_show-form | 
    // Assert Submit Form Button is present
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".contact-us__button_show-form"));
      assert(elements.size() > 0);
    }
  }
}
