// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class HomePageLogoTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void homePageLogo() {
    // Test name: homePageLogo
    // Step # | name | target | value
    // 1 | open | https://www.sportchek.ca/categories/fan-shop/nhl/seattle-kraken.html | 
    driver.get("https://www.sportchek.ca/categories/fan-shop/nhl/seattle-kraken.html");
    // 2 | setWindowSize | 1595x921 | 
    driver.manage().window().setSize(new Dimension(1595, 921));
    // 3 | mouseOver | id=headerPickupStoreTitle | 
    // Move mouse over to the logo in the top left corner
    {
      WebElement element = driver.findElement(By.id("headerPickupStoreTitle"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 4 | mouseOut | id=headerPickupStoreTitle | 
    // Move mouse over to the logo in the top left corner
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 5 | mouseOver | css=.header-search__submit | 
    // Move mouse over to the logo in the top left corner
    {
      WebElement element = driver.findElement(By.cssSelector(".header-search__submit"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 6 | mouseOut | css=.header-search__submit | 
    // Move mouse over to the logo in the top left corner
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 7 | mouseOver | linkText=Sport Chek | 
    // Move mouse over to the logo in the top left corner
    {
      WebElement element = driver.findElement(By.linkText("Sport Chek"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 8 | click | linkText=Sport Chek | 
    // Click on the logo
    driver.findElement(By.linkText("Sport Chek")).click();
    // 9 | assertElementPresent | linkText=Sport Chek | Sport Chek
    // Check that the Sport Chek homepage logo is present
    {
      List<WebElement> elements = driver.findElements(By.linkText("Sport Chek"));
      assert(elements.size() > 0);
    }
    // 10 | assertElementPresent | css=.full-image__img > img | The Joy of Training
    // Asser the Under Armor Joy of Training Image is present
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".full-image__img > img"));
      assert(elements.size() > 0);
    }
    // 11 | assertText | css=.page-nav__item:nth-child(3) .main-menu__text | Women
    // Verifiy that the Hompage tool button is visible
    assertThat(driver.findElement(By.cssSelector(".page-nav__item:nth-child(3) .main-menu__text")).getText(), is("Women"));
  }
}
