// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class MailingListSignupCalgaryTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void mailingListSignupCalgary() {
    // Open homepage
    driver.get("https://www.sportchek.ca/");
    // Make sure there is a sign-up button we can press
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".enterprise-header__section:nth-child(3) a:nth-child(1) > font"));
      assert(elements.size() > 0);
    }
    // Click Sign up For Mailing List
    driver.findElement(By.cssSelector(".enterprise-header__section:nth-child(3) a:nth-child(1) > font")).click();
    // Make sure there is a filed for email
    {
      List<WebElement> elements = driver.findElements(By.name("email"));
      assert(elements.size() > 0);
    }
    // Make sure there is a filed for postal code
    {
      List<WebElement> elements = driver.findElements(By.name("postalCode"));
      assert(elements.size() > 0);
    }
    // Make sure there is a filed for first name
    {
      List<WebElement> elements = driver.findElements(By.name("firstName"));
      assert(elements.size() > 0);
    }
    // Make sure there is a filed for last name
    {
      List<WebElement> elements = driver.findElements(By.name("lastName"));
      assert(elements.size() > 0);
    }
    // Type email
    driver.findElement(By.name("email")).sendKeys("yanortoraz@gmail.com");
    // Type postal code
    driver.findElement(By.name("postalCode")).sendKeys("T2N 4V5");
    // Type First Name
    driver.findElement(By.name("firstName")).sendKeys("Yanor");
    // Type Last Name
    driver.findElement(By.name("lastName")).sendKeys("Toraz");
    // Select "agree to T&C"
    driver.findElement(By.cssSelector(".checkbox")).click();
    // Click submit
    driver.findElement(By.cssSelector(".sign-up__submit")).click();
    // Make sure signup is a success!
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("h1"));
      assert(elements.size() > 0);
    }
  }
}
