// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SearchMensPantsTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void searchMensPants() {
    // Open homepage
    driver.get("https://www.sportchek.ca//");
    // Check to make sure search bar exists.
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".header-search__input"));
      assert(elements.size() > 0);
    }
    // Click on search bar
    driver.findElement(By.cssSelector(".header-search__input")).click();
    // Type in search critera
    driver.findElement(By.cssSelector(".header-search__input")).sendKeys("mens pants");
    // Press enter
    driver.findElement(By.cssSelector(".header-search__input")).sendKeys(Keys.ENTER);
    // Check to make sure the search results are returned.
    assertThat(driver.findElement(By.id("global-page-header__title")).getText(), is("SEARCH RESULTS: MENS PANTS"));
  }
}
