// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SetStoreTorontoTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void setStoreToronto() {
    // Open Homepage
    driver.get("https://www.sportchek.ca//");
    // Click select store
    driver.findElement(By.cssSelector(".header-pickup-store__link-container")).click();
    // Check to make sure we can enter a City or Postal Code
    assertThat(driver.findElement(By.cssSelector(".pickup-modal-choose__input-legend")).getText(), is("City or Postal Code"));
    // Click the postal code box
    driver.findElement(By.id("pickup-modal-choose__input")).click();
    // Type in your postal code
    driver.findElement(By.id("pickup-modal-choose__input")).sendKeys("M5K 1A2");
    // Make sure we can set this as our store (button exists).
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".pickup-store-list__item:nth-child(2) > .pickup-store-list__default-store"));
      assert(elements.size() > 0);
    }
    // Click submit
    driver.findElement(By.cssSelector(".pickup-modal-choose__submit")).click();
    // Choose appropriate store
    {
      WebElement element = driver.findElement(By.cssSelector(".pickup-modal-choose__submit"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // Click done
    driver.findElement(By.cssSelector(".pickup-store-list__item:nth-child(2) > .pickup-store-list__default-store")).click();
  }
}
