// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TrangleRewardsTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void trangleRewards() {
    // Test name: trangleRewards
    // Step # | name | target | value
    // 1 | open | https://www.sportchek.ca/ | 
    driver.get("https://www.sportchek.ca/");
    // 2 | setWindowSize | 1595x923 | 
    driver.manage().window().setSize(new Dimension(1595, 923));
    // 3 | mouseOver | css=.spo-meganav-item > .main-menu__text | 
    // Mouse over to the triangle rewards link at the top of the page
    {
      WebElement element = driver.findElement(By.cssSelector(".spo-meganav-item > .main-menu__text"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 4 | mouseOut | css=.spo-meganav-item > .main-menu__text | 
    // Mouse over to the triangle rewards link at the top of the page
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 5 | mouseOver | css=.full-image__img > img | 
    // Mouse over to the triangle rewards link at the top of the page
    {
      WebElement element = driver.findElement(By.cssSelector(".full-image__img > img"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 6 | mouseOut | css=.full-image__img > img | 
    // Mouse over to the triangle rewards link at the top of the page
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 7 | mouseOver | css=.full-image__img > img | 
    // Mouse over to the triangle rewards link at the top of the page
    {
      WebElement element = driver.findElement(By.cssSelector(".full-image__img > img"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 8 | mouseOut | css=.full-image__img > img | 
    // Mouse over to the triangle rewards link at the top of the page
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 9 | click | css=.enterprise-header__section:nth-child(2) font | 
    // Click on the triangle rewards link
    driver.findElement(By.cssSelector(".enterprise-header__section:nth-child(2) font")).click();
    // 10 | assertText | css=span > .module-font-32 | Redeem anytime, any amount at our great Brands.
    // Assert that the Triangle rewards Image is present
    assertThat(driver.findElement(By.cssSelector("span > .module-font-32")).getText(), is("Redeem anytime, any amount at our great Brands."));
    // 11 | click | css=#content_triangle-site_en_rewards-cards_jcr-content_content-paragraph_column-control-402686446_column-0-content_banner-builder b | 
    // Click on teh Join Now button
    driver.findElement(By.cssSelector("#content_triangle-site_en_rewards-cards_jcr-content_content-paragraph_column-control-402686446_column-0-content_banner-builder b")).click();
    // 12 | assertElementPresent | css=#register-site-login .gigya-input-submit | 
    // Assert that the Create Account Button is present in the dialog that pops up
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("#register-site-login .gigya-input-submit"));
      assert(elements.size() > 0);
    }
  }
}
